version: '2'

services:

  gateway-config:
    image: nebraltd/hm-config:711dd63
    depends_on:
      - dbus-session
      - diagnostics
    environment:
      - FIRMWARE_VERSION=2023.02.07.0-21
      - FIRMWARE_SHORT_HASH=6b33dea
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    restart: on-failure
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - miner-storage:/var/data
      - dbus:/session/dbus
      - nebra:/var/nebra
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.kernel-modules: 1
      io.balena.features.dbus: 1
    stop_signal: SIGINT

  packet-forwarder:
    image: nebraltd/hm-pktfwd:7a442f0
    depends_on:
      - multiplexer
    restart: always
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd
      - nebra:/var/nebra
    environment:
      - FIRMWARE_VERSION=2023.02.07.0-21
      - FIRMWARE_SHORT_HASH=6b33dea
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1

  multiplexer:
    image: nebraltd/hm-multiplexer:e44e6a4
    restart: always
    depends_on:
      - helium-miner
    expose:
      - "1681"
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
    volumes:
      - nebra:/var/nebra

  helium-miner:
    image: nebraltd/hm-miner:arm64-9b59111
    depends_on:
      - dbus-session
      - diagnostics
    expose:
      - "1680"
      - "4467"
    ports:
      - "44158:44158/tcp"
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
      - pktfwdr:/var/pktfwd
      - dbus:/session/dbus
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/i2c-1:/dev/i2c-1
    restart: on-failure
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
      - FIRMWARE_VERSION=2023.02.07.0-21
      - FIRMWARE_SHORT_HASH=6b33dea

  diagnostics:
    image: nebraltd/hm-diag:54a8478
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=2023.02.07.0-21
      - FIRMWARE_SHORT_HASH=6b33dea
      - DIAGNOSTICS_VERSION=54a8478
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - watchdog-log:/var/watchdog
      - nebra:/var/nebra
    ports:
      - "80:5000"
    cap_add:
      - SYS_RAWIO
    devices:
      - /dev/i2c-1:/dev/i2c-1
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyUSB2:/dev/ttyUSB2
      - /dev/ttyUSB3:/dev/ttyUSB3
    restart: always
    privileged: true
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: '1'

  dbus-session:
    image: balenablocks/dbus:rpi-0.0.2
    restart: always
    volumes:
      - dbus:/session/dbus
    environment:
      - DBUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
      - FIRMWARE_VERSION=2023.02.07.0-21
      - FIRMWARE_SHORT_HASH=6b33dea

volumes:
  miner-storage:
  miner-log:
  watchdog-log:
  pktfwdr:
  dbus:
  nebra: