version: '2'

services:

  gateway-config:
    image: nebraltd/hm-config:0b666ba
    depends_on:
      - dbus-session
      - helium-miner
      - diagnostics
    environment:
      - FIRMWARE_VERSION=v1.0.0-4
      - FIRMWARE_SHORT_HASH=60e2888
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    restart: on-failure
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - miner-storage:/var/data
      - dbus:/session/dbus
      - nebra:/var/nebra
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.kernel-modules: 1
      io.balena.features.dbus: 1
    stop_signal: SIGINT

  packet-forwarder:
    image: nebraltd/hm-pktfwd:ff950df
    depends_on:
      - multiplexer
    restart: always
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd
      - nebra:/var/nebra
    environment:
      - FIRMWARE_VERSION=v1.0.0-4
      - FIRMWARE_SHORT_HASH=60e2888
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1

  multiplexer:
    image: nebraltd/hm-multiplexer:a1fc09b
    restart: always
    depends_on:
      - helium-miner
    expose:
      - "1681"
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
    volumes:
      - nebra:/var/nebra
    environment:
      - FIRMWARE_VERSION=v1.0.0-4
      - FIRMWARE_SHORT_HASH=60e2888

  helium-miner:
    image: nebraltd/hm-gatewayrs:arm64-d8b6d17
    depends_on:
      - diagnostics
    expose:
      - "1680"
      - "4467"
    ports:
      - "44158:44158/tcp"
    cap_add:
      - SYS_RAWIO
    privileged: true
    restart: always
    environment:
      - FIRMWARE_VERSION=v1.0.0-4
      - FIRMWARE_SHORT_HASH=60e2888
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - nebra:/var/nebra

  diagnostics:
    image: nebraltd/hm-diag:arm64-4d92450
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=v1.0.0-4
      - FIRMWARE_SHORT_HASH=60e2888
      - DIAGNOSTICS_VERSION=4d92450
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - watchdog-log:/var/watchdog
      - nebra:/var/nebra
    ports:
      - "80:80"
    cap_add:
      - SYS_RAWIO
    restart: always
    privileged: true
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: '1'

  dbus-session:
    image: balenablocks/dbus:rpi-0.0.2
    restart: always
    volumes:
      - dbus:/session/dbus
    environment:
      - DBUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
      - FIRMWARE_VERSION=v1.0.0-4
      - FIRMWARE_SHORT_HASH=60e2888

volumes:
  miner-storage:
  pktfwdr:
  dbus:
  nebra:
  watchdog-log: