version: '2'

services:

  gateway-config:
    image: nebraltd/hm-config:1f564d0
    depends_on:
      - dbus-session
      - helium-miner
      - diagnostics
    environment:
      - FIRMWARE_VERSION=v1.0.0-0
      - FIRMWARE_SHORT_HASH=7a05b56
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    restart: on-failure
    privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - miner-storage:/var/data
      - dbus:/session/dbus
      - nebra:/var/nebra
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.kernel-modules: 1
      io.balena.features.dbus: 1
    stop_signal: SIGINT

  packet-forwarder:
    image: nebraltd/hm-pktfwd:c39fcf7
    depends_on:
      - multiplexer
    restart: always
    privileged: true
    network_mode: host
    extra_hosts:
        - "multiplexer:127.0.0.1"
    volumes:
      - pktfwdr:/var/pktfwd
      - nebra:/var/nebra
    environment:
      - FIRMWARE_VERSION=v1.0.0-0
      - FIRMWARE_SHORT_HASH=7a05b56
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1

  multiplexer:
    image: nebraltd/hm-multiplexer:a1fc09b
    restart: always
    depends_on:
      - helium-miner
    network_mode: host
    extra_hosts:
        - "helium-miner:127.0.0.1"
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
    volumes:
      - nebra:/var/nebra
    environment:
      - FIRMWARE_VERSION=v1.0.0-0
      - FIRMWARE_SHORT_HASH=7a05b56

  helium-miner:
    image: nebraltd/hm-gatewayrs:arm64-b0e27e1
    network_mode: host
    cap_add:
      - SYS_RAWIO
    privileged: true
    restart: always
    environment:
      - FIRMWARE_VERSION=v1.0.0-0
      - FIRMWARE_SHORT_HASH=7a05b56
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data

  diagnostics:
    image: nebraltd/hm-diag:arm64-5bc4892
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=v1.0.0-0
      - FIRMWARE_SHORT_HASH=7a05b56
      - DIAGNOSTICS_VERSION=5bc4892
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - watchdog-log:/var/watchdog
      - nebra:/var/nebra
    network_mode: host
    extra_hosts:
        - "helium-miner:127.0.0.1"
    cap_add:
      - SYS_RAWIO
    restart: always
    privileged: true
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: '1'

  dbus-session:
    image: balenablocks/dbus:rpi-0.0.2
    restart: always
    volumes:
      - dbus:/session/dbus
    environment:
      - DBUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
      - FIRMWARE_VERSION=v1.0.0-0
      - FIRMWARE_SHORT_HASH=7a05b56

volumes:
  miner-storage:
  pktfwdr:
  dbus:
  nebra:
  watchdog-log:

# balena keeps on changing the subnet, making it impossible
# to use extra_hosts for naming host IPs
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16