version: '2'

services:

  gateway-config:
    image: nebraltd/hm-config:arm64-eadeba8
    depends_on:
      - dbus-session
      - helium-miner
      - diagnostics
    environment:
      - FIRMWARE_VERSION=v1.0.2-48
      - FIRMWARE_SHORT_HASH=d88a08c
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    restart: on-failure
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - miner-storage:/var/data
      - dbus:/session/dbus
      - nebra:/var/nebra
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.kernel-modules: 1
      io.balena.features.dbus: 1
    stop_signal: SIGINT

  packet-forwarder:
    image: nebraltd/hm-pktfwd:c206d30
    depends_on:
      - multiplexer
    restart: always
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd
      - nebra:/var/nebra
    environment:
      - FIRMWARE_VERSION=v1.0.2-48
      - FIRMWARE_SHORT_HASH=d88a08c
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1

  multiplexer:
    image: nebraltd/hm-multiplexer:a1fc09b
    restart: always
    depends_on:
      - helium-miner
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
    volumes:
      - nebra:/var/nebra
    environment:
      - FIRMWARE_VERSION=v1.0.2-48
      - FIRMWARE_SHORT_HASH=d88a08c
    expose:
      - "1681"

  helium-miner:
    image: nebraltd/hm-gatewayrs:arm64-f8f5592
    depends_on:
      - diagnostics
    cap_add:
      - SYS_RAWIO
    privileged: true
    restart: always
    expose:
      - "1680"
      - "4467"
    ports:
      - "44158:44158/tcp"
    environment:
      - FIRMWARE_VERSION=v1.0.2-48
      - FIRMWARE_SHORT_HASH=d88a08c
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - nebra:/var/nebra

  diagnostics:
    image: nebraltd/hm-diag:arm64-e2ffec2
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=v1.0.2-48
      - FIRMWARE_SHORT_HASH=d88a08c
      - DIAGNOSTICS_VERSION=e2ffec2
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - GATEWAYRS_VERSION=f8f5592
      - CONFIG_VERSION=eadeba8
      - PKTFWD_VERSION=c206d30
      - MULTIPLEXER_VERSION=a1fc09b
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - watchdog-log:/var/watchdog
      - nebra:/var/nebra
    ports:
      - "80:80"
    cap_add:
      - SYS_RAWIO
    restart: always
    privileged: true
    labels:
      io.balena.features.sysfs: 1
      io.balena.features.procfs: 1
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1

  dbus-session:
    image: balenablocks/dbus:rpi-0.0.2
    restart: always
    volumes:
      - dbus:/session/dbus
    environment:
      - DBUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
      - FIRMWARE_VERSION=v1.0.2-48
      - FIRMWARE_SHORT_HASH=d88a08c

volumes:
  miner-storage:
  pktfwdr:
  dbus:
  nebra:
  watchdog-log: